name: ubuntu-build

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu-24-build:
    runs-on: ubuntu-24.04
    name: ubuntu-24-build
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends -y \
          python3 \
          python3-dev \
          python3-venv

      - name: Install Python dependencies
        run: |
          mkdir venv
          python3 -m venv --system-site-packages venv
          . venv/bin/activate
          python3 -m pip install --upgrade pip

      - name: Install terrain_nav_py
        run: |
          . venv/bin/activate
          python3 -m pip install .

      - name: Run tests in terrain_nav_py
        run: |
          . venv/bin/activate
          pytest .

  ubuntu-22-build:
    runs-on: ubuntu-22.04
    name: ubuntu-22-build
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends -y \
          python3 \
          python3-dev \
          python3-venv

      - name: Install Python dependencies
        run: |
          mkdir venv
          python3 -m venv --system-site-packages venv
          . venv/bin/activate
          python3 -m pip install --upgrade pip

      - name: Install terrain_nav_py
        run: |
          . venv/bin/activate
          python3 -m pip install .

      - name: Run tests in terrain_nav_py
        run: |
          . venv/bin/activate
          pytest .
