name: ubuntu-build

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    name: ubuntu-build
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends -y \
          python3 \
          python3-dev \
          python3-venv

      - name: Install Python dependencies
        run: |
          mkdir venv
          python3 -m venv --system-site-packages venv
          . venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install https://github.com/ompl/ompl/releases/download/prerelease/ompl-1.6.0-cp312-cp312-manylinux_2_28_x86_64.whl
          python3 -m pip install matplotlib
          python3 -m pip install mavproxy
          python3 -m pip install numpy
          python3 -m pip install pymavlink
          python3 -m pip install pytest

      - name: Install terrain_nav_py
        run: |
          . venv/bin/activate
          python3 -m pip install .

      - name: Run tests in terrain_nav_py
        run: |
          . venv/bin/activate
          pytest ./tests/test_dubins_airplane.py
          pytest ./tests/test_dubins_path.py
          pytest ./tests/test_grid_map.py
          pytest ./tests/test_ompl_setup.py
          pytest ./tests/test_path.py
          pytest ./tests/test_path_segment.py
          pytest ./tests/test_terrain_ompl_rrt.py
          pytest ./tests/test_terrain_ompl.py
          pytest ./tests/test_util.py

  ubuntu-22-build:
    runs-on: ubuntu-22.04
    name: ubuntu-22-build
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends -y \
          python3 \
          python3-dev \
          python3-venv

      - name: Install Python dependencies
        run: |
          mkdir venv
          python3 -m venv --system-site-packages venv
          . venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install https://github.com/ompl/ompl/releases/download/prerelease/ompl-1.6.0-cp310-cp310-manylinux_2_28_x86_64.whl
          python3 -m pip install matplotlib
          python3 -m pip install mavproxy
          python3 -m pip install numpy
          python3 -m pip install pymavlink
          python3 -m pip install pytest

      - name: Install terrain_nav_py
        run: |
          . venv/bin/activate
          python3 -m pip install .

      - name: Run tests in terrain_nav_py
        run: |
          . venv/bin/activate
          pytest ./tests/test_dubins_airplane.py
          pytest ./tests/test_dubins_path.py
          pytest ./tests/test_grid_map.py
          pytest ./tests/test_ompl_setup.py
          pytest ./tests/test_path.py
          pytest ./tests/test_path_segment.py
          pytest ./tests/test_terrain_ompl_rrt.py
          pytest ./tests/test_terrain_ompl.py
          pytest ./tests/test_util.py
